package com.richards.enums;

public enum ValidationResult {
    SUCCESS, FAILED, EMAIL_NOT_VALID, FIRSTNAME_NOT_VALID, SURNAME_NOT_VALID, PASSWORD_NOT_VALID, GENDER_NOT_VALID,
    USER_UNKNOWN, EMAIL_ALREADY_EXISTS, PASSWORD_MUST_BE_8_OR_MORE_CHARACTERS_LONG,
}
